[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs =
    .*
    venv
    __pycache__
    pytest-cache-files*
addopts =
    --ignore=venv
    --ignore-glob=pytest-cache-files-*
    -p no:cacheprovider
